In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [57]:
data = pd.read_csv('dataset.csv')
x_train = np.array(data['area'])
y_train = np.array(data['price'])
x_train , y_train 

(array([2600, 3000, 3200, 3600, 4000]),
 array([550000, 565000, 610000, 680000, 725000]))

In [58]:
x_mean = np.mean(x_train)
x_std = np.std(x_train)
y_mean = np.mean(y_train)
y_std = np.std(y_train)
print(100 * y_mean + y_std)

x_train = (x_train - x_mean)/x_std
y_train = (y_train - y_mean)/y_std

62667037.30304838


In [59]:
x_train, y_train


(array([-1.40693001, -0.57932412, -0.16552118,  0.66208471,  1.4896906 ]),
 array([-1.13369716, -0.90994114, -0.23867309,  0.80552167,  1.47678972]))

In [60]:
w , b = 0, 0

In [61]:
def predict_price(x_train, w, b):
    results = [0]* len(x_train)
    for i in range(len(x_train)):
        results[i] = x_train[i] * w + b

    return results

results = predict_price(x_train, w, b)
results

[0.0, 0.0, 0.0, 0.0, 0.0]

In [62]:
x = np.array(10)
print(x)

10


In [63]:
def compute_cost(x, y, w, b):
    cost = 0
    for i in range(len(x)):
        predict = w*x[i] + b
        a = y[i]
        cost += (predict - y[i])**2
    cost /= len(x)
    cost /= 2
    return cost

print(compute_cost(x_train, y_train , w , b))

0.5


In [64]:
def gradient_descent(x,y,a,w,b):
    new_w = 0
    dj_dw = 0
    dj_db = 0
    for i in range(len(x)):
        cost = (x[i]*w + b) - y[i]
        dj_dw += (cost * x[i])
        dj_db += cost
    new_w = w -  (a*(dj_dw / len(x)))
    new_b = b - (a*(dj_db / len(x)))
    return new_w, new_b


In [65]:
for i in range(10000):
    w, b = gradient_descent(x_train, y_train, 1, w, b)



In [66]:
w,b

(0.9789944401374039, 6.106226635439242e-17)

In [67]:
print(compute_cost(x_train, y_train, w, b))

0.020784943090025668


In [68]:
test_data = pd.read_csv('test_data.csv')
x_test = test_data['area']
y_test = test_data['price']

In [69]:
a = np.array(predict_price([(3150- x_mean)/x_std], w, b))
a * y_std + y_mean

array([608347.60273973])

In [70]:
a = np.array(predict_price((np.array([3300])- x_mean)/x_std, w, b))
a * y_std + y_mean


array([628715.75342466])

In [71]:
compute_cost((x_test- x_mean)/x_std, (y_test- y_mean)/y_std, w, b)

0.19337072143813744

In [72]:
print(w, b)

0.9789944401374039 6.106226635439242e-17
