In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import pickle

In [2]:
data = np.loadtxt("houses.txt", delimiter=',', skiprows=1)
X_train = data[:,:4]
y_train = data[:,4]
print(y_train)



[300.    509.8   394.    540.    415.    230.    560.    294.    718.2
 200.    302.    468.    374.2   388.    282.    311.8   401.    449.8
 301.    502.    340.    400.282 572.    264.    304.    298.    219.8
 490.7   216.96  368.2   280.    526.87  237.    562.426 369.8   460.
 374.    390.    158.    426.    390.    277.774 216.96  425.8   504.
 329.    464.    220.    358.    478.    334.    426.98  290.    463.
 390.8   354.    350.    460.    237.    288.304 282.    249.    304.
 332.    351.8   310.    216.96  666.336 330.    480.    330.3   348.
 304.    384.    316.    430.4   450.    284.    275.    414.    258.
 378.    350.    412.    373.    225.    390.    267.4   464.    174.
 340.    430.    440.    216.    329.    388.    390.    356.    257.8  ]


In [3]:
# X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
# y_train = np.array([460, 232, 178])

In [4]:
w = np.zeros(X_train.shape[1])
b = 0
w

array([0., 0., 0., 0.])

In [5]:
def predict_price(x,w,b):
    return np.dot(x,w) + b

In [6]:
def compute_cost(x, y, w, b):
    cost = 0
    return sum((np.dot(x,w) - y)**2) / (2*len(x))

In [7]:
# def compute_gradient(x, y, w, b):
#     dj_dw = np.zeros(w.shape[0])
#     dj_db = 0
#     for i in range(len(x)):
#         cost = np.dot(x[i],w) - y[i]
#         for j in range(len(w)):
#             dj_dw[j] += (cost * x[i,j])
#         dj_db += cost
#     return dj_dw/len(x), dj_db/len(x)

def compute_gradient(X, y, w, b): 
    """
    Computes the gradient for linear regression 
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters  
      b (scalar)       : model parameter
      
    Returns:
      dj_dw (ndarray (n,)): The gradient of the cost w.r.t. the parameters w. 
      dj_db (scalar):       The gradient of the cost w.r.t. the parameter b. 
    """
    m,n = X.shape           #(number of examples, number of features)
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * X[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_dw, dj_db 

In [8]:
def gradient_descent(x, y, w, b, iterations, alpha):
    for iteration in range(iterations):
        dj_dw, dj_db = compute_gradient(x,y,w,b)
        w = w - (alpha * dj_dw)
        b = b - (alpha * dj_db)
    return w, b

In [9]:
def normalize(X_train):
    mean = np.mean(X_train, axis=0)
    sd = np.std(X_train, axis=0)
    X_train = (X_train - mean)/sd
    return mean, sd, X_train
xmean, xsd, X_train = normalize(X_train)

In [10]:
print(X_train)

[[-4.23632450e-01  4.33808841e-01 -7.89272336e-01  9.93726440e-01]
 [ 1.28427160e+00  4.33808841e-01  1.26698980e+00 -8.29542143e-01]
 [ 7.44933479e-01  4.33808841e-01  1.26698980e+00  1.40281572e-01]
 [ 1.31342501e+00  4.33808841e-01  1.26698980e+00 -9.07128040e-01]
 [-2.53570880e-01 -1.10001528e+00 -7.89272336e-01 -9.45920989e-01]
 [-1.34682383e+00 -1.10001528e+00 -7.89272336e-01  1.07131234e+00]
 [ 1.01460254e+00  4.33808841e-01 -7.89272336e-01 -8.29542143e-01]
 [-9.53252767e-01  4.33808841e-01 -7.89272336e-01  1.79074520e-01]
 [ 4.31379699e+00  1.96763296e+00  1.26698980e+00  1.88596426e+00]
 [-1.53146210e+00 -1.10001528e+00 -7.89272336e-01  1.61441362e+00]
 [-5.30528294e-01 -1.10001528e+00  1.26698980e+00 -8.29542143e-01]
 [ 3.36785712e-01 -1.10001528e+00 -7.89272336e-01 -7.90749194e-01]
 [ 2.82454353e-02  4.33808841e-01 -7.89272336e-01 -7.13163297e-01]
 [-4.81939274e-01 -1.10001528e+00 -7.89272336e-01 -9.07128040e-01]
 [-7.92909002e-01 -1.10001528e+00 -7.89272336e-01  9.93726440e

In [12]:


initial_w = np.zeros(X_train.shape[1])
initial_b = 0.

print('initial_cost', compute_cost(X_train, y_train, w, b))
# some gradient descent settings
iterations = 100
alpha = 0.5
w,b = gradient_descent(X_train, y_train, initial_w, initial_b, iterations, alpha)

print('final_cost', compute_cost(X_train, y_train, w, b))
print(w, b)

initial_cost 66160.37633832518
final_cost 66160.37633832518
[110.56039664 -21.26715049 -32.70718088 -37.97015927] 363.1560808080808


In [13]:

# First, normalize out example.
x_house = np.array([1200, 3, 1, 40])
x_house_norm = (x_house - xmean) / xsd
print(x_house_norm)
x_house_predict = np.dot(x_house_norm, w) + b
print(f" predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = ${x_house_predict*1000:0.0f}")

[-0.53052829  0.43380884 -0.78927234  0.06269567]
 predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = $318709
