In [23]:
import numpy as np

In [24]:
X = np.array([0,0,0,1,1,0,1,1])
X = X.reshape(-1,2)
Y = np.array([0,1,1,1])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [25]:
X_train = np.c_[np.ones(X.shape[0]), X]

In [26]:
w = np.random.rand(X_train.shape[1])
w

array([0.55719108, 0.62616829, 0.96842206])

In [27]:
def sigmoid(x):
    return 1/ (1+ np.exp(-x))

In [28]:
def preditct(X,w):
    X = np.array(X)
    X = np.c_[np.ones(X.shape[0]), X]
    return sigmoid(np.dot(X, w))

In [29]:
def calculate_loss(X, y, w):
    y_pred = sigmoid(np.dot(X, w))

    loss = sum(- y * np.log(y_pred) - (1-y) * np.log(1-y_pred))
    return loss/len(X)

calculate_loss(X_train,Y,w)
    

np.float64(0.39600150020964753)

In [30]:
def calculate_gradients(X, y, w):
    y_pred = sigmoid(np.dot(X, w))
    error = y_pred - y

    wj = np.dot(error, X)
    return wj/len(X)

calculate_gradients(X_train, Y, w)


array([ 0.02963808, -0.0846534 , -0.07070033])

In [31]:
def gradient_descent(X, y, w, alpha, iterations):
    
    for i in range(iterations):
        if i % 1000 == 0:
            print(f'iteration {i} : loss {calculate_loss(X,y,w)}')
        wj = calculate_gradients(X,y,w)
        # print(wj)
        w = w - (alpha *wj)
        
    return w

In [32]:
alpha = 0.1
iterations = 10000
w = gradient_descent(X_train,Y,w, alpha, iterations)


iteration 0 : loss 0.39600150020964753
iteration 1000 : loss 0.29984195122376867
iteration 2000 : loss 0.2395560089819249
iteration 3000 : loss 0.19833358004203952
iteration 4000 : loss 0.16857742291138902


iteration 5000 : loss 0.1461728800265118
iteration 6000 : loss 0.1287446249975967
iteration 7000 : loss 0.11483370998075021
iteration 8000 : loss 0.10349607972572343
iteration 9000 : loss 0.09409446203368556


In [34]:
print(preditct([[0,0]], w))
print(preditct([[0,1]], w))
print(preditct([[1,0]], w))
print(preditct([[1,1]], w))

[0.17995888]
[0.93090155]
[0.92914515]
[0.99875935]
