In [35]:
import numpy as np

In [36]:
X = np.array([0,0,0,1,1,0,1,1])
X = X.reshape(-1,2)
Y = np.array([0,1,1,0])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [38]:
X_train = np.c_[np.ones(X.shape[0]), X]

In [39]:
w = np.random.rand(X_train.shape[1])
w

array([0.35203616, 0.38865574, 0.15071707, 0.61100004])

In [40]:
def sigmoid(x):
    return 1/ (1+ np.exp(-x))

In [41]:
def preditct(X,w):
    
    X = np.array(X)
    X = np.c_[np.ones(X.shape[0]), X]
    return sigmoid(np.dot(X, w))

In [42]:
def calculate_loss(X, y, w):
    y_pred = sigmoid(np.dot(X, w))

    loss = sum(- y * np.log(y_pred) - (1-y) * np.log(1-y_pred))
    return loss/len(X)

calculate_loss(X_train,Y,w)
    

np.float64(0.8627163663350619)

In [43]:
def calculate_gradients(X, y, w):
    y_pred = sigmoid(np.dot(X, w))
    error = y_pred - y

    wj = np.dot(error, X)
    return wj/len(X)

calculate_gradients(X_train, Y, w)


array([0.1763245 , 0.12377016, 0.11025991, 0.20448337])

In [44]:
def gradient_descent(X, y, w, alpha, iterations):
    
    for i in range(iterations):
        if i % 1000 == 0:
            print(f'iteration {i} : loss {calculate_loss(X,y,w)}')
        wj = calculate_gradients(X,y,w)
        # print(wj)
        w = w - (alpha *wj)
        
    return w

In [45]:
alpha = 0.01
iterations = 10000
w = gradient_descent(X_train,Y,w, alpha, iterations)


iteration 0 : loss 0.8627163663350619
iteration 1000 : loss 0.6131150490298304
iteration 2000 : loss 0.529336680708871
iteration 3000 : loss 0.46765184855437714


iteration 4000 : loss 0.41803151485505274
iteration 5000 : loss 0.37665957932331545
iteration 6000 : loss 0.3416039363398121
iteration 7000 : loss 0.311617978060414
iteration 8000 : loss 0.2857814099975546
iteration 9000 : loss 0.26337477639739554


In [49]:
print(preditct([[0,0]], w))

[0.31299057]


In [47]:

x = np.array([[1,2]])
x[:,1] * x[:,0]

array([2])